### ISSUE TITLE
Consider fitting the following Folia?

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [NaspoDev/Tether#7]
I hope your plugin will work with Folia, I love your plugin, but I'm sorry it doesn't work with Folia :(

**Comment by NaspoDev** [comment]
Hello! I might do this a little in the future. I might have to re-write some things to explicitly work with Folia. I will look into this more though.

**Comment by xiaoyueyoqwq** [comment]
> Hello! I might do this a little in the future. I might have to re-write some things to explicitly work with Folia. I will look into this more though.

Okay, thanks!
